@startuml
actor Użytkownik
Użytkownik -> "Aplikacja główna": Włącz grę
"Aplikacja główna" -> Gra: Włącz grę
loop użytkownik kontynuuje grę
Użytkownik -> "Aplikacja główna": Wykonaj ruch
"Aplikacja główna" -> Gra: Wykonaj ruch
Gra -> Algorytm: Wykonaj ruch
Algorytm --> Gra: Wykonaj ruch przeciwnika
Gra --> "Aplikacja główna": Wykonaj ruch przeciwnika
"Aplikacja główna" --> Użytkownik: Pokaż ruch wykonany przez przeciwnika
end
Użytkownik -> "Aplikacja główna": Zapisz drzewo do pliku
"Aplikacja główna" -> Serializacja: Zapisz drzewo do pliku
Serializacja --> Użytkownik: Zwróć plik
@enduml