@startuml
actor Użytkownik
alt użytkownik wczytuje drzewo podczas rozgrywki
Użytkownik -> "Aplikacja główna": Włącz grę
"Aplikacja główna" -> Gra: Włącz grę
loop użytkownik kontynuuje grę
Użytkownik -> "Aplikacja główna": Wykonaj ruch
"Aplikacja główna" -> Gra: Wykonaj ruch
Gra -> Algorytm: Wykonaj ruch
Algorytm --> Gra: Wykonaj ruch przeciwnika
Gra --> "Aplikacja główna": Wykonaj ruch przeciwnika
"Aplikacja główna" --> Użytkownik: Pokaż ruch wykonany przez przeciwnika
end
Użytkownik -> "Aplikacja główna": Analizuj drzewo
"Aplikacja główna" -> Wizualizacja: Analizuj drzewo
else użytkownik wczytuje drzewo z aplikacji głównej
Użytkownik -> "Aplikacja główna": Wczytaj plik drzewa
"Aplikacja główna" -> Serializacja: Zdeserializuj drzewo
Serializacja --> Wizualizacja: Wyświetl drzewo
end
Wizualizacja --> Użytkownik: Pokaż okno analizy drzewa
@enduml