@startuml
alt user choses analysis from menu
User -> Menu: Load tree file
User -> Menu: Analyze tree
Menu -> "Analyze tree": Analyze tree
else
User -> Menu: Play
Menu -> Game: Play
loop user continues playing
User -> Game: Make move
Game --> User: Make opponent's move
end
User -> "Analyze tree": Analyze tree
end
"Analyze tree" --> User: Return tree analysis window
@enduml