@startuml
actor Użytkownik
Użytkownik -> "Aplikacja główna": Włącz grę
"Aplikacja główna" -> Gra: Inicjalizuj grę
...użytkownik wykonuje ruchy...
Użytkownik -> "Aplikacja główna": Zapisz drzewo do pliku
"Aplikacja główna" -> Serializacja: Zapisz drzewo do pliku
Serializacja --> Użytkownik: Zwróć plik
@enduml