@startuml
class MonteCarloTree {
    {field} ""MonteCarloNode root""
    {field} ""BaseGameState game_state""
}

class MonteCarloNode {
    {field} ""int id""
    {field} ""BaseGameMove move""
    {field} ""MonteCarloNodeDetails details""
    {field} ""MonteCarloNodeVisualisationDetails vis_details""
    {field} ""MonteCarloNode[] children""
    {field} ""MonteCarloNode parent""
}


class MonteCarloNodeDetails {
    {field} ""String state_name""
    {field} ""String move_name""
    {field} ""int visits_count""
    {field} ""int visits_count_pre""
    {field} ""int win_score""
    {field} ""float average_prize""
}

class MonteCarloNodeVisualisationDetails {
    {field} ""float x""
    {field} ""float y""
}


MonteCarloTree o-- MonteCarloNode
MonteCarloNode o-- MonteCarloNodeDetails
MonteCarloNode o-- MonteCarloNodeVisualisationDetails
@enduml